#!/bin/bash

if [ "$(playerctl -p spotify status >>/dev/null 2>&1; echo $?)" == "1" ]
then
	echo "please open spotify"
	exit 0
fi

if [ "$(playerctl -p spotify status)" == "Playing" ]
then
	echo ""
else
	echo ""
fi