#!/bin/bash

if [ "$(playerctl -p spotify status >>/dev/null 2>&1; echo $?)" == "1" ]
then
	echo "[please open spotify]"
	exit 0
fi

if [ "$(playerctl -p spotify status)" == "Playing" ]
then
	title=$(playerctl -p spotify metadata xesam:title)
	artist=$(playerctl -p spotify metadata xesam:artist)
	echo "$title - $artist"
elif [ "$(playerctl -p spotify status)" == "Paused" ]
then
	title=$(playerctl -p spotify metadata xesam:title)
	artist=$(playerctl -p spotify metadata xesam:artist)
	echo "$title - $artist"
fi